import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    /* {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Extra',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    }, */
    {
      type: 'category',
      label: 'Gift Craft',
      items: [
        {
          type: 'doc',
          id: 'gift-craft/installation',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'gift-craft/plugin',
          label: 'Plugin',
        },
        {
          type: 'doc',
          id: 'gift-craft/widget',
          label: 'Widget',
        },
      ],
    },
  ],
};

export default sidebars;
